const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: '123456',
      isAdmin: true,
    },
    {
      name: 'Usuario',
      email: 'user@example.com',
      password: '123456',
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Air Force 1',
      slug: 'nike-air-force-1',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500',
      price: 110,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Tenis clásicos de alta calidad.',
    },
    {
      name: 'Adidas Ultraboost',
      slug: 'adidas-ultraboost',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=500',
      price: 140,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 12,
      description: 'Tenis deportivos con máxima amortiguación.',
    },
    {
      name: 'Puma Carina Street',
      slug: 'puma-carina-street',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500',
      price: 75,
      countInStock: 8,
      brand: 'Puma',
      rating: 4.6,
      numReviews: 7,
      description: 'Tenis urbanos de diseño casual.',
    },
    {
      name: 'Jordan 1 Retro High',
      slug: 'jordan-1-retro-high',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500',
      price: 180,
      countInStock: 5,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 20,
      description: 'Tenis icónicos estilo básquetbol.',
    },
    {
      name: 'Nike Dunk Low',
      slug: 'nike-dunk-low',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
      price: 130,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 15,
      description: 'Tenis modernos de estilo urbano.',
    },
    {
      name: 'Adidas Forum Low',
      slug: 'adidas-forum-low',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=500',
      price: 125,
      countInStock: 7,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 11,
      description: 'Diseño retro clásico.',
    },
    {
      name: 'New Balance 550',
      slug: 'new-balance-550',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=500',
      price: 150,
      countInStock: 6,
      brand: 'New Balance',
      rating: 4.9,
      numReviews: 18,
      description: 'Estilo clásico y cómodo.',
    },
    {
      name: 'Puma RS-X',
      slug: 'puma-rs-x',
      category: 'Tenis',
      image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=500',
      price: 95,
      countInStock: 12,
      brand: 'Puma',
      rating: 4.4,
      numReviews: 9,
      description: 'Diseño voluminoso y actual.',
    },
  ],
};

export default data;